/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Usuario;
import javax.swing.JOptionPane;

public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public static Usuario U;

    public static frmNuevoPedido frmNuevoPedido;
    public static frmNuevoCliente frmNuevoCliente;
    public static frmGestionarClientes frmGestionarClientes;
    public static frmGestionarPedidos frmGestionarPedidos;
    public static frmCambiarFechaRecojo frmCambiarFechaRecojo;
    public static frmListarPedidos frmListarPedidos;

    public frmPrincipal() {
        initComponents();
    }

    public frmPrincipal(Usuario U) {
        this.U = U;
        initComponents();
        setLocationRelativeTo(null);
        lblTipoUsuario.setText(U.getPuesto());
        lblNombre.setText(U.getNombre());
        if (U.getPuesto().equalsIgnoreCase("ventas")) {
            opcTaller.setEnabled(false);
        }
        if (U.getPuesto().equalsIgnoreCase("taller")) {
            opcVentas.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        lblTipoUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        opcVentas = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        opcListarPedidosVentas = new javax.swing.JMenuItem();
        opcTaller = new javax.swing.JMenu();
        opcListarPedidosTaller = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jToolBar1.setRollover(true);

        lblTipoUsuario.setText("tipoUsuario");
        jToolBar1.add(lblTipoUsuario);

        jLabel1.setText("      ");
        jToolBar1.add(jLabel1);

        lblNombre.setText("jLabel1");
        jToolBar1.add(lblNombre);

        opcVentas.setText("Ventas");

        jMenu4.setText("Clientes");

        jMenuItem5.setText("Nuevo Cliente");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Gestionar Clientes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        opcVentas.add(jMenu4);
        opcVentas.add(jSeparator1);

        jMenu5.setText("Pedidos");

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setText("Nuevo Pedido");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        opcListarPedidosVentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opcListarPedidosVentas.setText("Listar Pedidos");
        opcListarPedidosVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcListarPedidosVentasActionPerformed(evt);
            }
        });
        jMenu5.add(opcListarPedidosVentas);

        opcVentas.add(jMenu5);

        jMenuBar1.add(opcVentas);

        opcTaller.setText("Taller");
        opcTaller.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        opcListarPedidosTaller.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opcListarPedidosTaller.setText("Listar Pedidos");
        opcListarPedidosTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcListarPedidosTallerActionPerformed(evt);
            }
        });
        opcTaller.add(opcListarPedidosTaller);

        jMenuBar1.add(opcTaller);

        jMenu3.setText("Sistema");

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem4.setText("Cerrar sesión");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem7.setText("Salir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 458, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrarSesion();

    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (frmNuevoPedido == null) {
            frmNuevoPedido = new frmNuevoPedido();
        }
        frmNuevoPedido.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (frmGestionarClientes == null) {
            frmNuevoCliente = new frmNuevoCliente();
        }
        frmNuevoCliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if (frmGestionarClientes == null) {
            frmGestionarClientes = new frmGestionarClientes();
        }
        frmGestionarClientes.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void opcListarPedidosTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcListarPedidosTallerActionPerformed
        if (frmGestionarPedidos == null) {
            frmGestionarPedidos = new frmGestionarPedidos(true);
        }
        frmGestionarPedidos.setVisible(true);
    }//GEN-LAST:event_opcListarPedidosTallerActionPerformed

    private void opcListarPedidosVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcListarPedidosVentasActionPerformed
        if (frmListarPedidos == null) {
            frmListarPedidos = new frmListarPedidos();
        }
        frmListarPedidos.setVisible(true);
    }//GEN-LAST:event_opcListarPedidosVentasActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        cerrarSesion();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JMenuItem opcListarPedidosTaller;
    private javax.swing.JMenuItem opcListarPedidosVentas;
    private javax.swing.JMenu opcTaller;
    private javax.swing.JMenu opcVentas;
    // End of variables declaration//GEN-END:variables

    private void cerrarSesion() {
        int seleccion = JOptionPane.showOptionDialog(
                this,
                "Seleccione opcion",
                "Selector de opciones",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // null para icono por defecto.
                new Object[]{"Cerrar sesión", "Salir"}, // null para YES, NO y CANCEL
                "Cerrar sesión");
        switch (seleccion) {
            case 0: //Cerrar sesión
                if (frmGestionarClientes != null) {
                    frmGestionarClientes.dispose();
                }
                if (frmNuevoCliente != null) {
                    frmNuevoCliente.dispose();
                }
                if (frmNuevoPedido != null) {
                    frmNuevoPedido.dispose();
                }
                if (frmGestionarPedidos != null) {
                    frmGestionarPedidos.dispose();
                }
                if (frmCambiarFechaRecojo != null) {
                    frmCambiarFechaRecojo.dispose();
                }
                if (frmListarPedidos != null) {
                    frmListarPedidos.dispose();
                }
                this.dispose();
                new frmLogin().setVisible(true);
                break;
            case 1:
                System.exit(0);
                break;
        }
    }
}
